In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size 
voc_size = 10000

In [4]:
### one Hot represantation for every word 
one_hot_repr = [one_hot(words,voc_size) for words in sent]


In [5]:
one_hot_repr

[[1610, 9597, 3726, 7943],
 [1610, 9597, 3726, 4626],
 [1610, 4732, 3726, 3127],
 [862, 1390, 5235, 4632, 1361],
 [862, 1390, 5235, 4632, 2688],
 [6446, 1610, 4795, 3726, 5936],
 [6047, 1987, 9456, 4632]]

In [20]:
### word embedding reprasentation 

from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences


In [21]:
import numpy as np 


In [22]:
sent_length= 8 
embedded_docs = pad_sequences(one_hot_repr,padding="pre" , maxlen=sent_lenght)
print(embedded_docs)

[[   0    0    0    0 1610 9597 3726 7943]
 [   0    0    0    0 1610 9597 3726 4626]
 [   0    0    0    0 1610 4732 3726 3127]
 [   0    0    0  862 1390 5235 4632 1361]
 [   0    0    0  862 1390 5235 4632 2688]
 [   0    0    0 6446 1610 4795 3726 5936]
 [   0    0    0    0 6047 1987 9456 4632]]


In [23]:
## Feature Representation
dim = 10 

In [24]:

model = Sequential()
model.add(Input(shape=(sent_length,)))
model.add(Embedding(input_dim=voc_size, output_dim=dim))

model.compile(optimizer="adam", loss="mse")

In [25]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[[ 2.77527012e-02, -3.11154369e-02, -3.98484357e-02,
          4.20023091e-02,  3.02174203e-02, -4.82769385e-02,
         -2.93678772e-02, -3.83977965e-03,  8.49788263e-03,
          1.30110271e-02],
        [ 2.77527012e-02, -3.11154369e-02, -3.98484357e-02,
          4.20023091e-02,  3.02174203e-02, -4.82769385e-02,
         -2.93678772e-02, -3.83977965e-03,  8.49788263e-03,
          1.30110271e-02],
        [ 2.77527012e-02, -3.11154369e-02, -3.98484357e-02,
          4.20023091e-02,  3.02174203e-02, -4.82769385e-02,
         -2.93678772e-02, -3.83977965e-03,  8.49788263e-03,
          1.30110271e-02],
        [ 2.77527012e-02, -3.11154369e-02, -3.98484357e-02,
          4.20023091e-02,  3.02174203e-02, -4.82769385e-02,
         -2.93678772e-02, -3.83977965e-03,  8.49788263e-03,
          1.30110271e-02],
        [-6.81504607e-05,  8.62063095e-03, -4.41288240e-02,
         -6.03673607e-03, -4.00078781e-02,  1.61449648e-02,
         -9.13630798e-03, -4.03218158e-02, -3.428117

In [27]:
embedded_docs[0]

array([   0,    0,    0,    0, 1610, 9597, 3726, 7943], dtype=int32)